-- صيدلية عبدالهادي — FINAL SUPABASE SETUP
-- Run this AFTER 00_base_schema.sql and v1_0/v1_4 that you already ran.
-- Safe to run repeatedly.

create or replace function public.is_admin() returns boolean language sql stable as $$
 select coalesce(auth.jwt()->'app_metadata'->>'role','')='admin'; $$;

-- settings
create table if not exists public.pharmacy_settings(
 id bigint generated by default as identity primary key,
 pharmacy_name text not null default 'صيدلية عبدالهادي', pharmacist_name text not null default 'نصر عبدالهادي',
 phone text, whatsapp text, address text, maps_url text,
 opening_time text default '08:00', closing_time text default '00:00',
 show_prices_to_customers boolean not null default false, updated_at timestamptz not null default now()
);
insert into public.pharmacy_settings(pharmacy_name,pharmacist_name,phone,whatsapp,address,maps_url,opening_time,closing_time,show_prices_to_customers)
select 'صيدلية عبدالهادي','نصر عبدالهادي','0995008129','963995008129','الحاضر — شارع سيرياتيل جانب معرض الحاضر كارز','https://maps.app.goo.gl/ZQ9LvYcxYA4cnvYZ9','08:00','00:00',false
where not exists(select 1 from public.pharmacy_settings);
alter table public.pharmacy_settings enable row level security;
drop policy if exists "Public can read pharmacy settings" on public.pharmacy_settings;
create policy "Public can read pharmacy settings" on public.pharmacy_settings for select to anon,authenticated using(true);
drop policy if exists "Admins can update pharmacy settings" on public.pharmacy_settings;
create policy "Admins can update pharmacy settings" on public.pharmacy_settings for update to authenticated using(public.is_admin()) with check(public.is_admin());

-- Admin CRUD policies

do $$declare t text; begin
 foreach t in array array['products','batches','customers','orders','order_items','suppliers','purchases','purchase_items','sales','sale_items','prescriptions'] loop
  execute format('alter table public.%I enable row level security',t);
 end loop;
end$$;

drop policy if exists "admin products" on public.products; create policy "admin products" on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "public products read" on public.products; create policy "public products read" on public.products for select to anon,authenticated using(active=true and customer_visible=true);
drop policy if exists "admin batches" on public.batches; create policy "admin batches" on public.batches for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists "admin customers" on public.customers; create policy "admin customers" on public.customers for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin orders" on public.orders; create policy "admin orders" on public.orders for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin order items" on public.order_items; create policy "admin order items" on public.order_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin suppliers" on public.suppliers; create policy "admin suppliers" on public.suppliers for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin purchases" on public.purchases; create policy "admin purchases" on public.purchases for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin purchase items" on public.purchase_items; create policy "admin purchase items" on public.purchase_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin sales" on public.sales; create policy "admin sales" on public.sales for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin sale items" on public.sale_items; create policy "admin sale items" on public.sale_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin prescriptions" on public.prescriptions; create policy "admin prescriptions" on public.prescriptions for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Customer order creation: anon may create a customer and order, but cannot read the full admin tables.
drop policy if exists "public create customers" on public.customers;
create policy "public create customers" on public.customers for insert to anon,authenticated with check(true);
drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders for insert to anon,authenticated with check(status='new');
drop policy if exists "public create order items" on public.order_items;
create policy "public create order items" on public.order_items for insert to anon,authenticated with check(quantity>0 and unit_price>=0);

-- Audit log
create table if not exists public.audit_logs(
 id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), action text not null, entity_type text, entity_id uuid, details jsonb, created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists "admin audit read" on public.audit_logs; create policy "admin audit read" on public.audit_logs for select to authenticated using(public.is_admin());
drop policy if exists "admin audit insert" on public.audit_logs; create policy "admin audit insert" on public.audit_logs for insert to authenticated with check(public.is_admin());

-- Atomic sale RPC. Client sends JSON: [{product_id,quantity,unit_price}].
create or replace function public.complete_sale_atomic(p_items jsonb,p_discount numeric default 0,p_customer_id uuid default null)
returns uuid language plpgsql security invoker as $$
declare sale_id uuid:=gen_random_uuid(); it jsonb; b record; need numeric; take numeric; sub numeric:=0; total numeric;
begin
 if not public.is_admin() then raise exception 'Admin authorization required'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'Sale must contain items'; end if;
 insert into public.sales(id,customer_id,subtotal,discount,total,created_by) values(sale_id,p_customer_id,0,greatest(p_discount,0),0,auth.uid());
 for it in select * from jsonb_array_elements(p_items) loop
   need:=(it->>'quantity')::numeric; if need<=0 then raise exception 'Invalid quantity'; end if;
   for b in select id,quantity,purchase_price,expiry_date from public.batches where product_id=(it->>'product_id')::uuid and quantity>0 and (expiry_date is null or expiry_date>=current_date) order by expiry_date nulls last,id for update loop
     exit when need<=0; take:=least(need,b.quantity);
     update public.batches set quantity=quantity-take where id=b.id;
     insert into public.sale_items(sale_id,product_id,batch_id,quantity,unit_price,unit_cost) values(sale_id,(it->>'product_id')::uuid,b.id,take,(it->>'unit_price')::numeric,b.purchase_price);
     insert into public.stock_movements(product_id,batch_id,movement_type,quantity,reference_id,created_by) values((it->>'product_id')::uuid,b.id,'sale',-take,sale_id,auth.uid());
     sub:=sub+take*(it->>'unit_price')::numeric; need:=need-take;
   end loop;
   if need>0 then raise exception 'Insufficient non-expired stock for product %',(it->>'product_id'); end if;
 end loop;
 total:=greatest(sub-greatest(p_discount,0),0); update public.sales set subtotal=sub,total=total where id=sale_id;
 insert into public.audit_logs(user_id,action,entity_type,entity_id,details) values(auth.uid(),'complete_sale','sale',sale_id,jsonb_build_object('subtotal',sub,'discount',p_discount));
 return sale_id;
end; $$;
grant execute on function public.complete_sale_atomic(jsonb,numeric,uuid) to authenticated;

-- Integrity healthcheck compatible with batches.quantity
create or replace function public.production_healthcheck() returns jsonb language plpgsql security definer set search_path=public as $$
declare n bigint;e bigint;begin select count(*) into n from public.batches where quantity<0;select count(*) into e from public.batches where expiry_date<current_date and quantity>0;return jsonb_build_object('ok',n=0 and e=0,'negative_stock_batches',n,'expired_batches_with_stock',e,'checked_at',now());end;$$;
revoke all on function public.production_healthcheck() from public; grant execute on function public.production_healthcheck() to authenticated;
