from pathlib import Path
p=Path('/mnt/data/build45/src/main.jsx')
s=p.read_text()
# nav
s=s.replace("['reports','التقارير',TrendingUp],['suppliers','الموردون',Truck],", "['reports','التقارير',TrendingUp],['purchases','المشتريات',Receipt],['suppliers','الموردون',Truck],")
s=s.replace("<div><b>صيدلية عبدالهادي</b><span>لوحة الإدارة • v4.4.2</span></div>", "<div><b>صيدلية عبدالهادي</b><span>لوحة الإدارة • v4.5</span></div>")
s=s.replace("{tab==='reports'&&<Reports/>}{tab==='suppliers'&&<Suppliers/>}", "{tab==='reports'&&<Reports/>}{tab==='purchases'&&<Purchases/>}{tab==='suppliers'&&<Suppliers/>}")
# Replace Suppliers function with enhanced version
start=s.index('function Suppliers(){')
end=s.index('\nfunction Customers(){', start)
new_sup=r'''function Suppliers(){
 const empty={name:'',phone:'',address:'',notes:''};
 const [rows,setRows]=useState([]),[show,setShow]=useState(false),[editId,setEditId]=useState(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[detail,setDetail]=useState(null),[history,setHistory]=useState([]),[historyBusy,setHistoryBusy]=useState(false);
 const load=async()=>{setErr('');const {data,error}=await supabase.rpc('admin_list_suppliers');if(error){setErr(error.message);throw error}setRows(Array.isArray(data)?data:[])};
 useEffect(()=>{load().catch(()=>{})},[]);
 const save=async()=>{if(!form.name.trim())return alert('أدخل اسم المورد');setBusy(true);setErr('');try{const rpc=editId?'admin_update_supplier':'admin_create_supplier';const args=editId?{p_id:editId,p_name:form.name.trim(),p_phone:form.phone.trim()||null,p_address:form.address.trim()||null,p_notes:form.notes.trim()||null}:{p_name:form.name.trim(),p_phone:form.phone.trim()||null,p_address:form.address.trim()||null,p_notes:form.notes.trim()||null};const {error}=await supabase.rpc(rpc,args);if(error)throw error;setShow(false);setEditId(null);setForm(empty);await load()}catch(e){alert(e?.message||'تعذر حفظ المورد')}finally{setBusy(false)}};
 const remove=async(r)=>{if(!confirm(`حذف المورد «${r.name}»؟`))return;const {data,error}=await supabase.rpc('admin_delete_supplier',{p_id:r.id});if(error)alert(error.message);else if(!data)alert('لم يتم العثور على المورد');else load().catch(()=>{})};
 const openHistory=async(r)=>{setDetail(r);setHistoryBusy(true);try{const {data,error}=await supabase.rpc('admin_supplier_purchase_history',{p_supplier_id:r.id});if(error)throw error;setHistory(Array.isArray(data)?data:[])}catch(e){alert(e.message||'تعذر تحميل سجل المشتريات');setHistory([])}finally{setHistoryBusy(false)}};
 return <><PageHead title="الموردون" sub="إدارة الموردين وربطهم بكل فواتير المشتريات والدفعات" refresh={load} actions={<button className="primary" onClick={()=>{setEditId(null);setForm(empty);setShow(true)}}><Plus/> إضافة مورد</button>}/>{err&&<div className="error" style={{marginBottom:12}}>{err}</div>}<div className="tableWrap"><table><thead><tr><th>المورد</th><th>الهاتف</th><th>العنوان</th><th>المشتريات</th><th>آخر شراء</th><th>إجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="linkButton" onClick={()=>openHistory(r)}><b>{r.name}</b></button></td><td>{r.phone||'—'}</td><td>{r.address||'—'}</td><td><span className="activePill">سجل المشتريات</span></td><td>{r.created_at?localDateTime(r.created_at):'—'}</td><td className="actions"><button className="iconBtn" title="سجل المشتريات" onClick={()=>openHistory(r)}><Receipt/></button><button className="iconBtn" title="تعديل" onClick={()=>{setEditId(r.id);setForm({...empty,...r});setShow(true)}}>✏️</button><button className="iconBtn danger" onClick={()=>remove(r)}><Trash2/></button></td></tr>)}</tbody></table>{!rows.length&&!err&&<div className="emptyCart">لا يوجد موردون حالياً. اضغط «إضافة مورد» للبدء.</div>}</div>
 {show&&<Modal onClose={()=>{if(!busy)setShow(false)}} title={editId?'تعديل المورد':'إضافة مورد جديد'}><div className="formGrid"><label>اسم المورد *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} autoFocus/></label><label>الهاتف<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>العنوان<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>ملاحظات<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="primary full" disabled={busy} onClick={save}>{busy?'جارٍ الحفظ…':editId?'حفظ التعديلات':'إضافة المورد'}</button></Modal>}
 {detail&&<Modal onClose={()=>setDetail(null)} title={`سجل مشتريات المورد: ${detail.name}`}><div className="supplierSummary"><div><b>المورد</b><span>{detail.name}</span></div><div><b>الهاتف</b><span>{detail.phone||'—'}</span></div><div><b>عدد الفواتير</b><span>{history.length}</span></div><div><b>إجمالي الفواتير المعروضة</b><span>{money(history.reduce((a,x)=>a+Number(x.total||0),0))} ل.س</span></div></div>{historyBusy?<div className="muted">جارٍ تحميل السجل…</div>:<div className="tableWrap"><table><thead><tr><th>الفاتورة</th><th>التاريخ</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td><b>{x.invoice_number||String(x.id).slice(0,8)}</b></td><td>{x.invoice_date||localDateTime(x.created_at)}</td><td>{money(x.total)} ل.س</td><td>{x.status||'مستلمة'}</td></tr>)}</tbody></table>{!history.length&&<div className="emptyCart">لا توجد مشتريات مسجلة لهذا المورد بعد.</div>}</div>}</Modal>}
 </>}
'''
s=s[:start]+new_sup+s[end:]
# Insert Purchases before Customers
insert_at=s.index('\nfunction Customers(){')
purchase=r'''
function Purchases(){
 const emptyForm={supplier_id:'',invoice_number:'',invoice_date:localDateKey(new Date()),notes:''};
 const emptyLine={product_id:'',quantity:1,purchase_price:0,sale_price:0,expiry_date:''};
 const [rows,setRows]=useState([]),[suppliers,setSuppliers]=useState([]),[products,setProducts]=useState([]),[show,setShow]=useState(false),[detail,setDetail]=useState(null),[form,setForm]=useState(emptyForm),[lines,setLines]=useState([{...emptyLine}]),[busy,setBusy]=useState(false),[q,setQ]=useState('');
 const load=async()=>{const [a,b,c]=await Promise.all([supabase.rpc('admin_list_purchases'),supabase.rpc('admin_list_suppliers'),supabase.rpc('admin_get_products')]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;setRows(a.data||[]);setSuppliers(b.data||[]);setProducts(c.data||[])};
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 const addLine=()=>setLines(x=>[...x,{...emptyLine}]);
 const updateLine=(i,k,v)=>setLines(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r));
 const removeLine=i=>setLines(x=>x.length===1?[{...emptyLine}]:x.filter((_,n)=>n!==i));
 const chooseProduct=(i,id)=>{const p=products.find(x=>x.id===id);updateLine(i,'product_id',id);setLines(x=>x.map((r,n)=>n===i?{...r,product_id:id,purchase_price:p?.purchase_price??0,sale_price:p?.sale_price??0}:r))};
 const total=lines.reduce((a,x)=>a+Number(x.quantity||0)*Number(x.purchase_price||0),0);
 const save=async()=>{if(!form.supplier_id)return alert('اختر المورد');const valid=lines.filter(x=>x.product_id&&Number(x.quantity)>0&&x.expiry_date);if(!valid.length)return alert('أضف صنفاً واحداً على الأقل مع الكمية والصلاحية');setBusy(true);try{const {data,error}=await supabase.rpc('admin_create_purchase',{p_supplier_id:form.supplier_id,p_invoice_number:form.invoice_number.trim()||null,p_invoice_date:form.invoice_date||localDateKey(new Date()),p_notes:form.notes.trim()||null,p_items:valid.map(x=>({product_id:x.product_id,quantity:Number(x.quantity),purchase_price:Number(x.purchase_price)||0,sale_price:Number(x.sale_price)||0,expiry_date:x.expiry_date}))});if(error)throw error;setShow(false);setForm({...emptyForm,invoice_date:localDateKey(new Date())});setLines([{...emptyLine}]);await load();alert(`تم استلام الفاتورة بنجاح${data?.public_code?` — ${data.public_code}`:''}`)}catch(e){alert(e.message||'تعذر تسجيل المشتريات')}finally{setBusy(false)}};
 const openDetail=async(r)=>{const {data,error}=await supabase.rpc('admin_get_purchase_detail',{p_purchase_id:r.id});if(error)alert(error.message);else setDetail(data||null)};
 const filtered=rows.filter(r=>(`${r.invoice_number||''} ${r.supplier_name||''}`.toLowerCase()).includes(q.toLowerCase()));
 return <><PageHead title="المشتريات" sub="من فاتورة المورد إلى الدفعة والمخزون بشكل مترابط" refresh={load} actions={<button className="primary" onClick={()=>{setForm({...emptyForm,invoice_date:localDateKey(new Date())});setLines([{...emptyLine}]);setShow(true)}}><Plus/> فاتورة شراء جديدة</button>}/><div className="purchaseWorkflow"><div><b>1</b><span>المورد</span></div><div><b>2</b><span>فاتورة الشراء</span></div><div><b>3</b><span>دفعات المخزون</span></div><div><b>4</b><span>تتبع التكلفة</span></div></div><div className="toolbar"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث برقم الفاتورة أو اسم المورد…"/></div></div><div className="tableWrap"><table><thead><tr><th>رقم الفاتورة</th><th>المورد</th><th>التاريخ</th><th>الأصناف</th><th>الإجمالي</th><th>الحالة</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="clickRow" onClick={()=>openDetail(r)}><td><b>{r.invoice_number||String(r.id).slice(0,8)}</b></td><td>{r.supplier_name||'—'}</td><td>{r.invoice_date||localDateTime(r.created_at)}</td><td>{r.item_count||0}</td><td>{money(r.total)} ل.س</td><td><span className="activePill">{r.status||'مستلمة'}</span></td><td><button className="iconBtn" onClick={e=>{e.stopPropagation();openDetail(r)}}><FileText/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="emptyCart">لا توجد فواتير شراء.</div>}</div>
 {show&&<Modal onClose={()=>{if(!busy)setShow(false)}} title="فاتورة شراء جديدة"><div className="formGrid"><label>المورد *<select value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">اختر المورد</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>رقم فاتورة المورد<input value={form.invoice_number} onChange={e=>setForm({...form,invoice_number:e.target.value})} placeholder="مثلاً PUR-00125"/></label><label>تاريخ الفاتورة<input type="date" value={form.invoice_date} onChange={e=>setForm({...form,invoice_date:e.target.value})}/></label><label>ملاحظات<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="purchaseLines"><div className="cardHead"><h3>أصناف الفاتورة</h3><button className="secondaryAction" onClick={addLine}><Plus/> إضافة صنف</button></div>{lines.map((x,i)=><div className="purchaseLine" key={i}><select value={x.product_id} onChange={e=>chooseProduct(i,e.target.value)}><option value="">اختر الدواء</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {p.barcode||'بدون باركود'}</option>)}</select><input type="number" min="1" value={x.quantity} onChange={e=>updateLine(i,'quantity',e.target.value)} placeholder="الكمية"/><input type="number" min="0" value={x.purchase_price} onChange={e=>updateLine(i,'purchase_price',e.target.value)} placeholder="سعر الشراء"/><input type="number" min="0" value={x.sale_price} onChange={e=>updateLine(i,'sale_price',e.target.value)} placeholder="سعر المبيع"/><input type="date" value={x.expiry_date} onChange={e=>updateLine(i,'expiry_date',e.target.value)}/><button className="iconBtn danger" onClick={()=>removeLine(i)}><Trash2/></button></div>)}</div><div className="purchaseTotal"><span>إجمالي الفاتورة</span><b>{money(total)} ل.س</b></div><p className="muted">عند الحفظ: تُنشأ الفاتورة، وتُنشأ دفعة لكل صنف، وتُضاف الكمية للمخزون، ويُحفظ المورد وسعر الشراء والربط بالفاتورة.</p><button className="primary full" disabled={busy} onClick={save}>{busy?'جارٍ استلام الفاتورة…':'حفظ واستلام الفاتورة'}</button></Modal>}
 {detail&&<Modal onClose={()=>setDetail(null)} title={`فاتورة ${detail.invoice_number||String(detail.id).slice(0,8)}`}><div className="supplierSummary"><div><b>المورد</b><span>{detail.supplier_name||'—'}</span></div><div><b>التاريخ</b><span>{detail.invoice_date||'—'}</span></div><div><b>الإجمالي</b><span>{money(detail.total)} ل.س</span></div><div><b>الحالة</b><span>{detail.status||'مستلمة'}</span></div></div><h3>أصناف الفاتورة والدفعات</h3><div className="tableWrap"><table><thead><tr><th>الدواء</th><th>الكمية</th><th>سعر الشراء</th><th>سعر المبيع</th><th>الصلاحية</th><th>رقم الدفعة</th></tr></thead><tbody>{(detail.items||[]).map(x=><tr key={x.id}><td><b>{x.product_name||'—'}</b><small>{x.barcode||''}</small></td><td>{x.quantity}</td><td>{money(x.purchase_price)} ل.س</td><td>{money(x.sale_price)} ل.س</td><td>{x.expiry_date||'—'}</td><td>{x.batch_id?String(x.batch_id).slice(0,8):'—'}</td></tr>)}</tbody></table></div><p className="muted">كل دفعة في هذه الفاتورة مرتبطة بالمورد نفسه، ويمكن تتبعها من بطاقة المادة والمخزون.</p></Modal>}
 </>}
'''
s=s[:insert_at]+purchase+s[insert_at:]
# Enhance ProductCard batch query + headers by replacing exact snippets
s=s.replace("select('id,expiry_date,quantity,purchase_price,received_date').eq('product_id',r.id).order('expiry_date')", "select('id,expiry_date,quantity,purchase_price,received_date,supplier_id,purchase_id,suppliers(name),purchases(invoice_number)').eq('product_id',r.id).order('expiry_date')")
s=s.replace("<tr><th>الصلاحية</th><th>الكمية</th><th>سعر النت</th><th>حذف</th></tr>", "<tr><th>المورد</th><th>الفاتورة</th><th>الصلاحية</th><th>الكمية</th><th>سعر النت</th><th>حذف</th></tr>")
s=s.replace("<tr key={b.id}><td>{b.expiry_date||'—'}</td><td><input className=\"qtyInput\"", "<tr key={b.id}><td>{b.suppliers?.name||'—'}</td><td>{b.purchases?.invoice_number||'—'}</td><td>{b.expiry_date||'—'}</td><td><input className=\"qtyInput\"")
# There are two identical ProductCard-like tables; second replacement may affect InventoryCard too, but that's desirable only if matching. Fix colSpan isn't present.
# Inventory openCard query
s=s.replace("select('id,expiry_date,quantity,purchase_price,received_date').eq('product_id',r.product_id).order('expiry_date')", "select('id,expiry_date,quantity,purchase_price,received_date,supplier_id,purchase_id,suppliers(name),purchases(invoice_number)').eq('product_id',r.product_id).order('expiry_date')")
# InventoryCard header/body exact
s=s.replace("<h3>الدفعات</h3>{busy?", "<h3>الدفعات — المورد والفاتورة مصدر التوريد</h3>{busy?")
s=s.replace("<tr><th>الصلاحية</th><th>الكمية</th><th>سعر النت</th><th>حذف</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td>{b.expiry_date||'—'}</td>", "<tr><th>المورد</th><th>الفاتورة</th><th>الصلاحية</th><th>الكمية</th><th>سعر النت</th><th>حذف</th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td>{b.suppliers?.name||'—'}</td><td>{b.purchases?.invoice_number||'—'}</td><td>{b.expiry_date||'—'}</td>")
p.write_text(s)
