-- Pharmacy Abdelhadi v4.5.2.1
-- 1) One source of truth for quantity editing: inventory only.
-- 2) Purchase creation/deletion are visible in Security/Audit.
BEGIN;

CREATE OR REPLACE FUNCTION public.admin_delete_purchase(p_purchase_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_supplier_id uuid;
  v_supplier_name text;
  v_invoice text;
  v_total numeric;
  v_items jsonb;
  v_sold_count integer;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin authorization required'; END IF;

  SELECT p.supplier_id, s.name, p.invoice_number, p.total
    INTO v_supplier_id, v_supplier_name, v_invoice, v_total
  FROM public.purchases p
  LEFT JOIN public.suppliers s ON s.id=p.supplier_id
  WHERE p.id=p_purchase_id;

  IF NOT FOUND THEN RAISE EXCEPTION 'Purchase invoice not found'; END IF;

  SELECT count(*)::integer INTO v_sold_count
  FROM public.sale_items si
  JOIN public.batches b ON b.id=si.batch_id
  WHERE b.purchase_id=p_purchase_id;

  IF v_sold_count > 0 THEN
    RAISE EXCEPTION 'Cannot delete this purchase invoice because one or more batches have already been sold';
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'product_name',pr.name,
    'quantity',pi.quantity,
    'purchase_price',pi.purchase_price,
    'expiry_date',pi.expiry_date
  ) ORDER BY pi.id),'[]'::jsonb)
  INTO v_items
  FROM public.purchase_items pi
  JOIN public.products pr ON pr.id=pi.product_id
  WHERE pi.purchase_id=p_purchase_id;

  -- Remove the stock movement generated by this receipt, then its batch/items.
  DELETE FROM public.stock_movements sm
  USING public.batches b
  WHERE sm.batch_id=b.id AND b.purchase_id=p_purchase_id;
  DELETE FROM public.purchase_items WHERE purchase_id=p_purchase_id;
  DELETE FROM public.batches WHERE purchase_id=p_purchase_id;
  DELETE FROM public.purchases WHERE id=p_purchase_id;

  INSERT INTO public.audit_logs(user_id,action,entity_type,entity_id,details)
  VALUES(
    auth.uid(),'admin_delete_purchase','purchase',p_purchase_id,
    jsonb_build_object(
      'supplier_id',v_supplier_id,
      'supplier_name',v_supplier_name,
      'invoice_number',v_invoice,
      'total',v_total,
      'items',v_items
    )
  );

  RETURN jsonb_build_object('id',p_purchase_id,'invoice_number',v_invoice,'deleted',true);
END;
$$;
REVOKE ALL ON FUNCTION public.admin_delete_purchase(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_delete_purchase(uuid) TO authenticated;

COMMIT;
