import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {Search,LogIn,LogOut,Package,ShoppingCart,ClipboardList,Users,Truck,BarChart3,ShieldCheck,Plus,Trash2,RefreshCw,Menu,Home,Upload,Eye,Minus} from 'lucide-react';
import './style.css';

const url=import.meta.env.VITE_SUPABASE_URL; const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createClient(url,key):null;
const CFG={name:'صيدلية عبدالهادي',owner:'نصر عبدالهادي',phone:'0995008129',whatsapp:'963995008129',address:'الحاضر — شارع سيرياتيل جانب معرض الحاضر كارز',hours:'8:00 صباحاً — 12:00 منتصف الليل',maps:'https://maps.app.goo.gl/ZQ9LvYcxYA4cnvYZ9'};
const money=v=>Number(v||0).toLocaleString('ar-SY',{maximumFractionDigits:2});
function App(){const [session,setSession]=useState(null); const [admin,setAdmin]=useState(false); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setAdmin(data.session?.user?.app_metadata?.role==='admin');setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setAdmin(s?.user?.app_metadata?.role==='admin')});return()=>subscription.unsubscribe()},[]);
 if(loading)return <Splash/>; if(!supabase)return <ConfigError/>; return admin?<Admin onLogout={()=>supabase.auth.signOut()}/>:<Customer session={session}/>}
function Splash(){return <div className="splash"><div className="logo">ص</div><h1>صيدلية عبدالهادي</h1><p>جاري تشغيل النظام…</p></div>}
function ConfigError(){return <div className="center"><h1>إعداد النظام غير مكتمل</h1><p>أضف VITE_SUPABASE_URL و VITE_SUPABASE_PUBLISHABLE_KEY في Vercel ثم أعد النشر.</p></div>}
function Customer(){const [products,setProducts]=useState([]),[q,setQ]=useState(''),[cart,setCart]=useState([]),[open,setOpen]=useState(false); const load=async()=>{const {data}=await supabase.from('products').select('id,name,active_ingredient,dosage_form,strength,manufacturer,category,unit,sale_price').eq('customer_visible',true).order('name') ;setProducts(data||[])}; useEffect(()=>{load()},[]); const shown=products.filter(p=>(p.name+' '+(p.active_ingredient||'')+' '+(p.manufacturer||'')).toLowerCase().includes(q.toLowerCase())); const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]}); const wa=()=>{const text=`طلب من ${CFG.name}%0A${cart.map(x=>`- ${x.name} × ${x.qty}`).join('%0A')}%0A%0Aالاسم:%0Aالهاتف:%0Aالعنوان:`;window.open(`https://wa.me/${CFG.whatsapp}?text=${text}`,'_blank')}; return <div><header className="top"><div className="brand"><div className="logo small">ص</div><div><b>{CFG.name}</b><span>{CFG.owner}</span></div></div><button className="cartBtn" onClick={()=>setOpen(true)}><ShoppingCart/> السلة <em>{cart.reduce((a,x)=>a+x.qty,0)}</em></button></header><section className="hero"><div><span>أهلاً بك</span><h1>دواؤك بثقة،<br/>وخدمة تليق بك.</h1><p>{CFG.address}</p><a href={CFG.maps} target="_blank">موقع الصيدلية على الخريطة</a></div></section><main className="customer"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن اسم الدواء أو المادة الفعالة…"/></div><div className="notice">أسعار المنتجات غير معروضة للزبائن. للاستفسار أو الطلب أضف المنتجات إلى السلة وأرسلها عبر واتساب.</div><div className="grid">{shown.map(p=><article className="product" key={p.id}><div className="pill">{p.dosage_form||'دواء'}</div><h3>{p.name}</h3><p>{[p.strength,p.active_ingredient].filter(Boolean).join(' · ')}</p><small>{p.manufacturer||'—'}</small><button onClick={()=>add(p)}><Plus/> إضافة للطلب</button></article>)}</div></main>{open&&<div className="modal"><div className="modalBox"><button className="x" onClick={()=>setOpen(false)}>×</button><h2>طلبك</h2>{!cart.length?<p>السلة فارغة.</p>:<>{cart.map(x=><div className="line" key={x.id}><span>{x.name}</span><b>× {x.qty}</b></div>)}<button className="primary full" onClick={wa}>إرسال الطلب عبر واتساب</button></>}</div></div>}</div>}
function Admin({onLogout}){const [tab,setTab]=useState('dashboard'),[mobile,setMobile]=useState(false); const nav=[['dashboard','الرئيسية',Home],['pos','نقطة البيع',ShoppingCart],['products','المنتجات',Package],['inventory','المخزون',BarChart3],['orders','الطلبات',ClipboardList],['prescriptions','الوصفات',Upload],['suppliers','الموردون',Truck],['customers','العملاء',Users],['security','الأمان',ShieldCheck]];return <div className="adminShell"><aside className={mobile?'open':''}><div className="sideBrand"><div className="logo">ص</div><div><b>صيدلية عبدالهادي</b><span>لوحة الإدارة</span></div></div>{nav.map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setMobile(false)}} key={id}><I/>{label}</button>)}<button className="logout" onClick={onLogout}><LogOut/> تسجيل الخروج</button></aside><main className="adminMain"><div className="mobileBar"><button onClick={()=>setMobile(!mobile)}><Menu/></button><b>{nav.find(x=>x[0]===tab)?.[1]}</b></div>{tab==='dashboard'&&<Dashboard/>}{tab==='pos'&&<POS/>}{tab==='products'&&<Products/>}{tab==='inventory'&&<Inventory/>}{tab==='orders'&&<Orders/>}{tab==='prescriptions'&&<Prescriptions/>}{tab==='suppliers'&&<Suppliers/>}{tab==='customers'&&<Customers/>}{tab==='security'&&<Security/>}</main></div>}
function Card({title,value,icon:I}){return <div className="kpi"><div><span>{title}</span><strong>{value}</strong></div><I/></div>}
function Dashboard(){const [s,setS]=useState({products:0,batches:0,orders:0,customers:0});const load=async()=>{const [[p],[b],[o],[c]] = await Promise.all(['products','batches','orders','customers'].map(async t=>{const {count}=await supabase.from(t).select('*',{count:'exact',head:true});return [count||0]}));setS({products:p,batches:b,orders:o,customers:c})};useEffect(()=>{load()},[]);return <><PageHead title="لوحة التحكم" sub="نظرة سريعة على الصيدلية" refresh={load}/><div className="kpis"><Card title="المنتجات" value={s.products} icon={Package}/><Card title="الدفعات" value={s.batches} icon={BarChart3}/><Card title="الطلبات" value={s.orders} icon={ClipboardList}/><Card title="العملاء" value={s.customers} icon={Users}/></div><div className="card"><h2>حالة النظام</h2><p>قاعدة البيانات متصلة. أسعار الزبائن مخفية. ملفات الوصفات محفوظة في bucket خاص.</p></div></>}
function PageHead({title,sub,refresh}){const [busy,setBusy]=useState(false);const run=async()=>{if(!refresh)return;setBusy(true);try{await refresh()}catch(e){alert(e?.message||'تعذر تحديث البيانات')}finally{setBusy(false)}};return <div className="pageHead"><div><h1>{title}</h1><p>{sub}</p></div>{refresh&&<button className="refreshBtn" onClick={run} disabled={busy}><RefreshCw className={busy?'spin':''}/>{busy?'جاري التحديث':'تحديث'}</button>}</div>}
function Products(){
 const empty={name:'',barcode:'',active_ingredient:'',strength:'',dosage_form:'',manufacturer:'',category:'',unit:'piece',reorder_level:0,sale_price:0,customer_visible:true};
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[show,setShow]=useState(false),[editId,setEditId]=useState(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false);
 const load=async()=>{let z=supabase.from('products').select('*').order('name');if(q)z=z.or(`name.ilike.%${q}%,barcode.ilike.%${q}%,active_ingredient.ilike.%${q}%`);const {data,error}=await z;if(error)throw error;setRows(data||[])};
 useEffect(()=>{load().catch(e=>console.warn(e))},[q]);
 const openNew=()=>{setEditId(null);setForm(empty);setShow(true)};
 const openEdit=r=>{setEditId(r.id);setForm({...empty,...r});setShow(true)};
 const save=async()=>{if(!form.name.trim())return alert('أدخل اسم المنتج');setBusy(true);try{const payload={name:form.name.trim(),barcode:form.barcode||null,active_ingredient:form.active_ingredient||null,strength:form.strength||null,dosage_form:form.dosage_form||null,manufacturer:form.manufacturer||null,category:form.category||null,unit:form.unit||'piece',reorder_level:Number(form.reorder_level)||0,sale_price:Number(form.sale_price)||0,customer_visible:!!form.customer_visible};const r=editId?supabase.from('products').update(payload).eq('id',editId):supabase.from('products').insert(payload);const {error}=await r;if(error)throw error;setShow(false);await load()}catch(e){alert(e.message||'تعذر حفظ المنتج')}finally{setBusy(false)}};
 const remove=async r=>{if(!confirm(`حذف/تعطيل المنتج «${r.name}»؟`))return;setBusy(true);try{const {count,error:ce}=await supabase.from('batches').select('id',{count:'exact',head:true}).eq('product_id',r.id);if(ce)throw ce;if((count||0)>0){const {error}=await supabase.from('products').update({customer_visible:false}).eq('id',r.id);if(error)throw error;alert('للمنتج دفعات مرتبطة، لذلك تم تعطيله بدل الحذف.')}else{const {error}=await supabase.from('products').delete().eq('id',r.id);if(error)throw error;alert('تم حذف المنتج.')}await load()}catch(e){alert(e.message||'تعذر حذف المنتج')}finally{setBusy(false)}};
 return <><PageHead title="المنتجات" sub="إدارة أصناف الأدوية وأسعار البيع" refresh={load}/><div className="toolbar"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالاسم أو الباركود أو المادة الفعالة…"/></div><button className="primary" onClick={openNew}><Plus/> منتج جديد</button></div><div className="tableWrap"><table><thead><tr><th>الدواء</th><th>المادة الفعالة</th><th>الشركة</th><th>سعر البيع</th><th>الحد الأدنى</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.strength||''} {r.dosage_form||''}</small></td><td>{r.active_ingredient||'—'}</td><td>{r.manufacturer||'—'}</td><td>{money(r.sale_price)}</td><td>{r.reorder_level}</td><td>{r.customer_visible?'ظاهر':'مخفي'}</td><td className="actions"><button className="iconBtn" title="تعديل" onClick={()=>openEdit(r)}>✏️</button><button className="iconBtn danger" title="حذف أو تعطيل" onClick={()=>remove(r)}><Trash2/></button></td></tr>)}</tbody></table></div>{show&&<ProductForm form={form} setForm={setForm} save={save} close={()=>setShow(false)} edit={!!editId} busy={busy}/>}</>}
function ProductForm({form,setForm,save,close,edit,busy}){const fields=[['name','اسم المنتج'],['barcode','الباركود'],['active_ingredient','المادة الفعالة'],['strength','العيار'],['dosage_form','الشكل الصيدلاني'],['manufacturer','الشركة'],['category','التصنيف'],['unit','الوحدة'],['reorder_level','حد إعادة الطلب'],['sale_price','سعر البيع']];return <div className="modal"><div className="modalBox wide"><button className="x" onClick={close}>×</button><h2>{edit?'تعديل المنتج':'إضافة منتج'}</h2><div className="formGrid">{fields.map(([k,l])=><label key={k}>{l}<input type={['reorder_level','sale_price'].includes(k)?'number':'text'} min="0" value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="check"><input type="checkbox" checked={!!form.customer_visible} onChange={e=>setForm({...form,customer_visible:e.target.checked})}/> إظهار المنتج للزبائن</label></div><button className="primary full" onClick={save} disabled={busy}>{busy?'جارٍ الحفظ…':edit?'حفظ التعديلات':'حفظ المنتج'}</button></div></div>}
function Inventory(){
 const empty={product_id:'',batch_number:'',expiry_date:'',quantity:0,purchase_price:0};
 const [rows,setRows]=useState([]),[products,setProducts]=useState([]),[show,setShow]=useState(false),[edit,setEdit]=useState(null),[adjust,setAdjust]=useState(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false);
 const load=async()=>{const {data,error}=await supabase.from('batches').select('id,batch_number,expiry_date,quantity,purchase_price,product_id,received_date,products(name,barcode)').order('expiry_date');if(error)throw error;setRows(data||[])};
 const loadProducts=async()=>{const {data,error}=await supabase.from('products').select('id,name,barcode').order('name');if(error)throw error;setProducts(data||[])};
 useEffect(()=>{Promise.all([load(),loadProducts()]).catch(e=>console.warn(e))},[]);const refresh=async()=>Promise.all([load(),loadProducts()]);
 const openNew=()=>{setEdit(null);setForm(empty);setShow(true)};const openEdit=r=>{setEdit(r);setForm({product_id:r.product_id,batch_number:r.batch_number||'',expiry_date:r.expiry_date||'',quantity:r.quantity,purchase_price:r.purchase_price||0});setShow(true)};
 const save=async()=>{if(!form.product_id)return alert('اختر المنتج');if(!form.expiry_date)return alert('أدخل تاريخ الانتهاء');if(Number(form.quantity)<=0)return alert('أدخل كمية أكبر من صفر');setBusy(true);try{if(edit){const {error}=await supabase.from('batches').update({batch_number:form.batch_number||null,expiry_date:form.expiry_date,purchase_price:Number(form.purchase_price)||0}).eq('id',edit.id);if(error)throw error;if(Number(form.quantity)!==Number(edit.quantity)){const delta=Number(form.quantity)-Number(edit.quantity);const {error:e}=await supabase.rpc('adjust_stock',{p_batch_id:edit.id,p_delta:delta,p_note:'تعديل كمية الدفعة من لوحة الإدارة'});if(e)throw e}}else{const payload={product_id:form.product_id,batch_number:form.batch_number||null,expiry_date:form.expiry_date,quantity:Number(form.quantity),purchase_price:Number(form.purchase_price)||0,received_date:new Date().toISOString().slice(0,10)};const {error}=await supabase.from('batches').insert(payload);if(error)throw error}setShow(false);await refresh()}catch(e){alert(e.message||'تعذر حفظ الدفعة')}finally{setBusy(false)}};
 const doAdjust=async()=>{const delta=Number(adjust?.delta);if(!delta)return alert('أدخل كمية التعديل');setBusy(true);try{const {error}=await supabase.rpc('adjust_stock',{p_batch_id:adjust.id,p_delta:delta,p_note:adjust.note||'تسوية مخزون'});if(error)throw error;setAdjust(null);await load()}catch(e){alert(e.message||'تعذر تعديل المخزون')}finally{setBusy(false)}};
 const remove=async r=>{if(Number(r.quantity)!==0)return alert('لا يمكن حذف دفعة فيها كمية. استخدم تعديل المخزون وأنقصها إلى صفر أولاً.');if(!confirm(`حذف الدفعة ${r.batch_number||r.id}؟`))return;const {error}=await supabase.from('batches').delete().eq('id',r.id);if(error)alert(error.message);else await load()};
 return <><PageHead title="المخزون والدفعات" sub="FEFO — الأقرب انتهاءً أولاً مع سجل حركات" refresh={refresh}/><div className="toolbar"><div><b>إدارة الدفعات والمخزون</b><p className="muted">التعديل الكمي يتم عبر حركة مخزون مسجلة.</p></div><button className="primary" onClick={openNew}><Plus/> إضافة دفعة</button></div><div className="tableWrap"><table><thead><tr><th>المنتج</th><th>الدفعة</th><th>الانتهاء</th><th>الكمية</th><th>سعر الشراء</th><th>إجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.products?.name||r.product_id}<small>{r.products?.barcode||''}</small></td><td>{r.batch_number||'—'}</td><td>{r.expiry_date||'—'}</td><td><b>{r.quantity}</b></td><td>{money(r.purchase_price)}</td><td className="actions"><button className="iconBtn" title="تعديل الدفعة" onClick={()=>openEdit(r)}>✏️</button><button className="iconBtn" title="زيادة/إنقاص المخزون" onClick={()=>setAdjust({id:r.id,delta:'',note:''})}>↕️</button><button className="iconBtn danger" title="حذف الدفعة" onClick={()=>remove(r)}><Trash2/></button></td></tr>)}</tbody></table></div>{show&&<BatchForm form={form} setForm={setForm} products={products} save={save} close={()=>setShow(false)} edit={!!edit} busy={busy}/>} {adjust&&<div className="modal"><div className="modalBox"><button className="x" onClick={()=>setAdjust(null)}>×</button><h2>تعديل كمية المخزون</h2><p className="muted">استخدم رقمًا موجبًا للزيادة وسالبًا للإنقاص.</p><input type="number" step="0.01" value={adjust.delta} onChange={e=>setAdjust({...adjust,delta:e.target.value})} placeholder="مثال: 10 أو -2"/><input value={adjust.note} onChange={e=>setAdjust({...adjust,note:e.target.value})} placeholder="سبب التعديل (اختياري)"/><button className="primary full" onClick={doAdjust} disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ حركة المخزون'}</button></div></div>}</>}
function BatchForm({form,setForm,products,save,close,edit,busy}){return <div className="modal"><div className="modalBox wide"><button className="x" onClick={close}>×</button><h2>{edit?'تعديل الدفعة':'إضافة دفعة / مخزون'}</h2><div className="formGrid"><label>المنتج<select disabled={edit} value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">اختر المنتج…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.barcode?` — ${p.barcode}`:''}</option>)}</select></label><label>رقم التشغيلة<input value={form.batch_number} onChange={e=>setForm({...form,batch_number:e.target.value})}/></label><label>تاريخ الانتهاء<input type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})}/></label><label>الكمية<input type="number" min="0" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>سعر الشراء للوحدة<input type="number" min="0" step="0.01" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/></label></div>{edit&&<p className="muted">إذا تغيرت الكمية سيتم تسجيل الفرق تلقائيًا في سجل حركات المخزون.</p>}<button className="primary full" onClick={save} disabled={busy}>{busy?'جارٍ الحفظ…':edit?'حفظ تعديلات الدفعة':'حفظ الدفعة'}</button></div></div>}
function POS(){const [q,setQ]=useState(''),[products,setProducts]=useState([]),[cart,setCart]=useState([]);useEffect(()=>{const t=setTimeout(async()=>{if(!q)return setProducts([]);const {data}=await supabase.from('products').select('*').ilike('name',`%${q}%`).limit(8);setProducts(data||[])},250);return()=>clearTimeout(t)},[q]);const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});return <><PageHead title="نقطة البيع" sub="إضافة المبيعات مع تحضيرها لتطبيق FEFO"/><div className="pos"><div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن الدواء…"/></div>{products.map(p=><button className="result" key={p.id} onClick={()=>add(p)}><span>{p.name}</span><small>{p.strength||''}</small></button>)}</div><div className="card"><h2>السلة</h2>{cart.length?cart.map(x=><div className="line" key={x.id}><span>{x.name}</span><div><button className="mini" onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus/></button> {x.qty} <button className="mini" onClick={()=>add(x)}><Plus/></button></div></div>):<p>لم تتم إضافة أصناف.</p>}<div className="notice">إتمام البيع النهائي يجب أن يتم عبر RPC ذري في قاعدة البيانات لمنع البيع بأكثر من المخزون.</div></div></div></>}
function Orders(){const [rows,setRows]=useState([]);const load=async()=>{const {data,error}=await supabase.from('orders').select('*,customers(name,phone)').order('created_at',{ascending:false}).limit(100);if(error)throw error;setRows(data||[])};useEffect(()=>{load().catch(e=>console.warn(e))},[]);const status=async(id,s)=>{const {error}=await supabase.from('orders').update({status:s}).eq('id',id);if(error)alert(error.message);else await load()};return <><PageHead title="الطلبات" sub="طلبات الزبائن وحالات التجهيز" refresh={load}/><div className="tableWrap"><table><thead><tr><th>العميل</th><th>الهاتف</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.customers?.name||'—'}</td><td>{r.customers?.phone||'—'}</td><td><select value={r.status} onChange={e=>status(r.id,e.target.value)}>{['new','confirmed','preparing','ready','completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td><td>{new Date(r.created_at).toLocaleString('ar')}</td></tr>)}</tbody></table></div></>}
function Prescriptions(){const [rows,setRows]=useState([]),[file,setFile]=useState(null),[busy,setBusy]=useState(false);const load=async()=>{const {data,error}=await supabase.from('prescriptions').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;setRows(data||[])};useEffect(()=>{load().catch(e=>console.warn(e))},[]);const upload=async()=>{if(!file)return alert('اختر ملف الوصفة أولاً');const allowed=['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(file.type))return alert('نوع الملف غير مسموح');if(file.size>10*1024*1024)return alert('حجم الملف يتجاوز 10 MB');setBusy(true);let path=null;try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('انتهت جلسة الدخول. سجّل الدخول مجددًا.');if(user.app_metadata?.role!=='admin')throw new Error('الحساب الحالي ليس مديرًا.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=`${crypto.randomUUID()}-${safe}`;const {error:upErr}=await supabase.storage.from('prescriptions').upload(path,file,{contentType:file.type,upsert:false});if(upErr)throw upErr;const {error:dbErr}=await supabase.from('prescriptions').insert({file_path:path,file_name:file.name,mime_type:file.type,file_size:file.size,created_by:user.id});if(dbErr){await supabase.storage.from('prescriptions').remove([path]);throw dbErr}setFile(null);const input=document.getElementById('rx-file');if(input)input.value='';await load();alert('تم رفع الوصفة بأمان.')}catch(e){alert(`تعذر رفع الوصفة: ${e.message||e}`)}finally{setBusy(false)}};const view=async path=>{const {data,error}=await supabase.storage.from('prescriptions').createSignedUrl(path,300);if(error)alert(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')};return <><PageHead title="الوصفات الطبية" sub="Private Storage — روابط مؤقتة للعرض" refresh={load}/><div className="upload card"><input id="rx-file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" onClick={upload} disabled={!file||busy}><Upload/> {busy?'جارٍ الرفع…':'رفع الوصفة'}</button></div><div className="tableWrap"><table><thead><tr><th>الملف</th><th>الحجم</th><th>التاريخ</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.file_name||r.file_path}</td><td>{Math.round((r.file_size||0)/1024)} KB</td><td>{new Date(r.created_at).toLocaleString('ar')}</td><td><button className="iconBtn" onClick={()=>view(r.file_path)}><Eye/></button></td></tr>)}</tbody></table></div></>}
function Suppliers(){const [rows,setRows]=useState([]),[name,setName]=useState('');const load=async()=>{const {data,error}=await supabase.from('suppliers').select('*').order('name');if(error)throw error;setRows(data||[])};useEffect(()=>{load().catch(e=>console.warn(e))},[]);const add=async()=>{if(!name.trim())return;const {error}=await supabase.from('suppliers').insert({name:name.trim()});if(error)alert(error.message);else{setName('');await load()}};return <><PageHead title="الموردون" sub="بيانات شركات وموردي الأدوية" refresh={load}/><div className="toolbar"><input className="simpleInput" value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المورد"/><button className="primary" onClick={add}><Plus/> إضافة</button></div><div className="tableWrap"><table><thead><tr><th>المورد</th><th>الهاتف</th><th>العنوان</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.phone||'—'}</td><td>{r.address||'—'}</td></tr>)}</tbody></table></div></>}
function Customers(){const [rows,setRows]=useState([]);const load=async()=>{const {data,error}=await supabase.from('customers').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;setRows(data||[])};useEffect(()=>{load().catch(e=>console.warn(e))},[]);return <><PageHead title="العملاء" sub="قاعدة بيانات العملاء" refresh={load}/><div className="tableWrap"><table><thead><tr><th>الاسم</th><th>الهاتف</th><th>العنوان</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.phone||'—'}</td><td>{r.address||'—'}</td></tr>)}</tbody></table></div></>}
function Security(){const [logs,setLogs]=useState([]);const load=async()=>{const {data,error}=await supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;setLogs(data||[])};useEffect(()=>{load().catch(e=>console.warn(e))},[]);return <><PageHead title="الأمان والتدقيق" sub="مراقبة السجلات وسلامة الوصول" refresh={load}/><div className="card"><h2>حساب المدير</h2><p>تم الدخول عبر Supabase Auth، والوصول الإداري يعتمد على app_metadata.role = admin.</p></div><div className="tableWrap"><table><thead><tr><th>العملية</th><th>التاريخ</th><th>المعرف</th></tr></thead><tbody>{logs.map(r=><tr key={r.id}><td>{r.action||'—'}</td><td>{new Date(r.created_at).toLocaleString('ar')}</td><td>{r.id}</td></tr>)}</tbody></table></div></>}
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setErr('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message)};return <div className="login"><form onSubmit={submit}><div className="logo">ص</div><h1>صيدلية عبدالهادي</h1><p>تسجيل دخول الإدارة</p><input type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary full"><LogIn/> دخول</button>{err&&<div className="error">{err}</div>}</form></div>}
// If a session exists but is not admin, show login instead of exposing admin.
const Root=()=>{const [s,setS]=useState(null),[checked,setChecked]=useState(false);useEffect(()=>{supabase?.auth.getSession().then(({data})=>{setS(data.session);setChecked(true)});if(supabase){const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,ss)=>setS(ss));return()=>subscription.unsubscribe()}},[]);if(!checked)return <Splash/>;if(s?.user?.app_metadata?.role==='admin')return <Admin onLogout={()=>supabase.auth.signOut()}/>;return <CustomerOrLogin/>};
function CustomerOrLogin(){const [login,setLogin]=useState(location.hash==='#admin');return login?<><Login/><button className="back" onClick={()=>{location.hash='';setLogin(false)}}>العودة للموقع</button></>:<><Customer/><button className="adminLink" onClick={()=>{location.hash='admin';setLogin(true)}}>دخول الإدارة</button></>}
createRoot(document.getElementById('root')).render(<Root/>);
